const defaults = {
    DEFAULT_CATEGORY_PAGE_SIZE: 12,
    DEFAULT_CATEGORY_CUSTOM_PAGINATION: true,
    DEFAULT_CATEGORY_SHOW: true,
    DEFAULT_CATEGORY_DISPLAY_ORDER: 1,
    
    DEFAULT_PRODUCT_INDIVIDUAL_VISIBILITY: true,
    DEFAULT_PRODUCT_SHOW: true,
    DEFAULT_PRODUCT_DISPLAY_ORDER: 1,
    
    DEFAULT_PRODUCTCATEGORY_FEATURE: true,
    DEFAULT_PRODUCTCATEGORY_SHOW: true,
    DEFAULT_PRODUCTCATEGORY_DISPLAY_ORDER: 1
};

module.exports = defaults;